/*
 * SPDX-FileCopyrightText: Copyright 2024, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from gen_utils.py tool file.
 * Date: 2024-09-12 18:43:07.572150
 ***************************************************************************/

#include "InputFiles.hpp"

static const char* imgFilenames[] = {
    "1-Normal.jpg",
    "2-CloseEye.jpg",
    "3-Yawning.jpg",
    "4-YawningCloseEye.jpg",
    "5-FaceDown.jpg",
};

static const uint8_t* imgArrays[] = {
    im0,
    im1,
    im2,
    im3,
    im4
};

static const int imgWidths[] = {
    im0_width,
    im1_width,
    im2_width,
    im3_width,
    im4_width
};

static const int imgHeights[] = {
    im0_height,
    im1_height,
    im2_height,
    im3_height,
    im4_height
};

const char* GetFilename(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgFilenames[idx];
    }
    return nullptr;
}

const uint8_t* GetImgArray(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgArrays[idx];
    }
    return nullptr;
}

const int GetImgWidth(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgWidths[idx];
    }
    return 0;
}

const int GetImgHeight(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgHeights[idx];
    }
    return 0;
}