/*
 * SPDX-FileCopyrightText: Copyright 2024, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from gen_utils.py tool file.
 * Date: 2024-09-12 18:43:07.572150
 ***************************************************************************/

#ifndef GENERATED_IMAGES_H
#define GENERATED_IMAGES_H

#include <cstdint>

#define NUMBER_OF_FILES (5U)
#define IMAGE_DATA_SIZE (691200U)

extern const int im0_width;
extern const int im0_height;

extern const uint8_t im0[IMAGE_DATA_SIZE];
extern const int im1_width;
extern const int im1_height;

extern const uint8_t im1[IMAGE_DATA_SIZE];
extern const int im2_width;
extern const int im2_height;

extern const uint8_t im2[IMAGE_DATA_SIZE];
extern const int im3_width;
extern const int im3_height;

extern const uint8_t im3[IMAGE_DATA_SIZE];
extern const int im4_width;
extern const int im4_height;

extern const uint8_t im4[IMAGE_DATA_SIZE];

/**
 * @brief       Gets the filename for the baked-in input array
 * @param[in]   idx     Index of the input.
 * @return      const C string pointer to the name.
 **/
const char* GetFilename(const uint32_t idx);

/**
 * @brief       Gets the pointer to image data.
 * @param[in]   idx     Index of the input.
 * @return      Pointer to the 8-bit unsigned integer data.
 **/
const uint8_t* GetImgArray(const uint32_t idx);

/**
 * @brief       Gets the pointer to image width.
 * @param[in]   idx     Index of the input.
 * @return      Image width.
 **/
const int GetImgWidth(const uint32_t idx);

/**
 * @brief       Gets the pointer to image height.
 * @param[in]   idx     Index of the input.
 * @return      Image Height.
 **/
const int GetImgHeight(const uint32_t idx);

#endif /* GENERATED_IMAGES_H */